package com.kakeibo.backend.config

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import com.auth0.jwt.interfaces.DecodedJWT
import com.kakeibo.shared.constants.AppConstants
import io.ktor.server.application.*
import java.security.SecureRandom
import java.util.*

class JwtConfig(environment: ApplicationEnvironment) {
    private val jwtConfig = environment.config.config("jwt")
    val secret: String = jwtConfig.property("secret").getString().also { secret ->
        require(secret.length >= 32) {
            "JWT secret must be at least 32 characters. Set the JWT_SECRET environment variable."
        }
        validateSecret(secret, isProduction = System.getenv("KTOR_ENV") == "production")
    }
    val issuer: String = jwtConfig.property("issuer").getString()
    val audience: String = jwtConfig.property("audience").getString()
    val realm: String = jwtConfig.property("realm").getString()

    private val algorithm = Algorithm.HMAC256(secret)
    private val secureRandom = SecureRandom()

    fun generateAccessToken(userId: String, username: String): String {
        return JWT.create()
            .withIssuer(issuer)
            .withAudience(audience)
            .withClaim("user_id", userId)
            .withClaim("username", username)
            .withExpiresAt(Date(System.currentTimeMillis() + AppConstants.ACCESS_TOKEN_EXPIRY_SECONDS * 1000L))
            .sign(algorithm)
    }

    /**
     * リフレッシュトークンを暗号学的に安全な乱数で生成する。
     * 32 バイト (256 bit) のエントロピーを Base64URL でエンコード。
     */
    fun generateRefreshToken(): String {
        val bytes = ByteArray(32)
        secureRandom.nextBytes(bytes)
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
    }

    fun verifyToken(token: String): DecodedJWT {
        val verifier = JWT.require(algorithm)
            .withIssuer(issuer)
            .withAudience(audience)
            .build()
        return verifier.verify(token)
    }

    fun getAlgorithm(): Algorithm = algorithm

    companion object {
        // 環境問わず常に拒否する既知のデフォルト/ドキュメント例値。
        internal val UNIVERSALLY_FORBIDDEN_SECRETS: Set<String> = setOf(
            "change-me-in-production-use-a-long-random-string-at-least-256-bits"
        )

        // 本番のみ拒否するプレースホルダー部分文字列 (小文字比較)。
        // 「明らかに開発用文字列」を検出して、`openssl rand` で生成した値への置換を強制する。
        internal val PRODUCTION_FORBIDDEN_PATTERNS: List<String> = listOf(
            "change-me", "change_me", "changeme",
            "your-secret", "your_secret",
            "replace-me", "replace_me",
            "to-be-changed", "to_be_changed",
            "dev_jwt", "dev-jwt"
        )

        /**
         * JWT_SECRET の弱値検証。
         * 本番 (KTOR_ENV=production) では既知のプレースホルダーパターンも拒否する。
         * dev/test では `UNIVERSALLY_FORBIDDEN_SECRETS` のみ拒否し、テスト用ランダム文字列は通す。
         */
        internal fun validateSecret(secret: String, isProduction: Boolean) {
            require(secret !in UNIVERSALLY_FORBIDDEN_SECRETS) {
                "JWT secret must be changed from the documented default value. Set the JWT_SECRET environment variable to a strong value (e.g. generated by 'openssl rand -base64 48')."
            }
            if (!isProduction) return

            val lowered = secret.lowercase()
            val matched = PRODUCTION_FORBIDDEN_PATTERNS.firstOrNull { it in lowered }
            require(matched == null) {
                "JWT secret contains a placeholder pattern ('$matched') and looks like an example value. Generate a strong one with: openssl rand -base64 48"
            }
        }
    }
}
