package com.kakeibo.backend.db

import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.javatime.*
import org.jetbrains.exposed.sql.json.jsonb

// =========================================
// Users
// =========================================
object Users : Table("users") {
    val id = uuid("id").autoGenerate()
    val username = varchar("username", 50)
    val passwordHash = varchar("password_hash", 255)
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Refresh Tokens
// =========================================
object RefreshTokens : Table("refresh_tokens") {
    val id = uuid("id").autoGenerate()
    val userId = uuid("user_id").references(Users.id)
    val tokenHash = varchar("token_hash", 64)
    val expiresAt = timestampWithTimeZone("expires_at")
    val createdAt = timestampWithTimeZone("created_at")
    val revokedAt = timestampWithTimeZone("revoked_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Accounts
// =========================================
object Accounts : Table("accounts") {
    val id = uuid("id")
    val name = varchar("name", 100)
    val type = varchar("type", 20)
    val initialBalance = long("initial_balance")
    val currency = varchar("currency", 3)
    val sortOrder = integer("sort_order")
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Categories
// =========================================
object Categories : Table("categories") {
    val id = uuid("id")
    val name = varchar("name", 50)
    val type = varchar("type", 10)
    val icon = varchar("icon", 50).nullable()
    val color = varchar("color", 7).nullable()
    val sortOrder = integer("sort_order")
    val isDefault = bool("is_default")
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Tags
// =========================================
object Tags : Table("tags") {
    val id = uuid("id")
    val name = varchar("name", 50)
    val color = varchar("color", 7).nullable()
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Transactions
// =========================================
object Transactions : Table("transactions") {
    val id = uuid("id")
    val type = varchar("type", 10)
    val amount = long("amount")
    val currency = varchar("currency", 3)
    val date = datetime("date")
    val memo = text("memo").nullable()
    val categoryId = uuid("category_id").references(Categories.id)
    val accountId = uuid("account_id").references(Accounts.id)
    val isAutoGenerated = bool("is_auto_generated")
    val recurringTransactionId = uuid("recurring_transaction_id").references(RecurringTransactions.id).nullable()
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Transaction Tags
// =========================================
object TransactionTags : Table("transaction_tags") {
    val transactionId = uuid("transaction_id").references(Transactions.id)
    val tagId = uuid("tag_id").references(Tags.id)
    override val primaryKey = PrimaryKey(transactionId, tagId)
}

// =========================================
// Transaction History
// =========================================
object TransactionHistory : Table("transaction_history") {
    val id = uuid("id").autoGenerate()
    val transactionId = uuid("transaction_id").references(Transactions.id)
    val userId = uuid("user_id").references(Users.id)
    val changedFields = jsonb<String>("changed_fields", { it }, { it })
    val changedAt = timestampWithTimeZone("changed_at")
    val versionBefore = integer("version_before")
    val versionAfter = integer("version_after")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Transfers
// =========================================
object Transfers : Table("transfers") {
    val id = uuid("id")
    val fromAccountId = uuid("from_account_id").references(Accounts.id)
    val toAccountId = uuid("to_account_id").references(Accounts.id)
    val amount = long("amount")
    val currency = varchar("currency", 3)
    val date = date("date")
    val memo = text("memo").nullable()
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Recurring Transactions
// =========================================
object RecurringTransactions : Table("recurring_transactions") {
    val id = uuid("id")
    val type = varchar("type", 10)
    val amount = long("amount")
    val currency = varchar("currency", 3)
    val categoryId = uuid("category_id").references(Categories.id)
    val accountId = uuid("account_id").references(Accounts.id)
    val frequency = varchar("frequency", 10)
    val interval = integer("interval")
    val dayOfMonth = integer("day_of_month").nullable()
    val dayOfWeek = integer("day_of_week").nullable()
    val monthOfYear = integer("month_of_year").nullable()
    val startDate = date("start_date")
    val endDate = date("end_date").nullable()
    val nextExecutionDate = date("next_execution_date")
    val memo = text("memo").nullable()
    val isActive = bool("is_active")
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Recurring Transaction Tags
// =========================================
object RecurringTransactionTags : Table("recurring_transaction_tags") {
    val recurringTransactionId = uuid("recurring_transaction_id").references(RecurringTransactions.id)
    val tagId = uuid("tag_id").references(Tags.id)
    override val primaryKey = PrimaryKey(recurringTransactionId, tagId)
}

// =========================================
// Budgets
// =========================================
object Budgets : Table("budgets") {
    val id = uuid("id")
    val categoryId = uuid("category_id").references(Categories.id)
    val yearMonth = varchar("year_month", 7)
    val amount = long("amount")
    val currency = varchar("currency", 3)
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Templates
// =========================================
object Templates : Table("templates") {
    val id = uuid("id")
    val name = varchar("name", 100)
    val type = varchar("type", 10)
    val amount = long("amount").nullable()
    val currency = varchar("currency", 3)
    val categoryId = uuid("category_id").references(Categories.id).nullable()
    val accountId = uuid("account_id").references(Accounts.id).nullable()
    val memo = text("memo").nullable()
    val useCount = integer("use_count")
    val lastUsedAt = timestampWithTimeZone("last_used_at").nullable()
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Template Tags
// =========================================
object TemplateTags : Table("template_tags") {
    val templateId = uuid("template_id").references(Templates.id)
    val tagId = uuid("tag_id").references(Tags.id)
    override val primaryKey = PrimaryKey(templateId, tagId)
}

// =========================================
// Input Patterns
// =========================================
object InputPatterns : Table("input_patterns") {
    val id = uuid("id")
    val keyword = varchar("keyword", 200)
    val categoryId = uuid("category_id").references(Categories.id).nullable()
    val accountId = uuid("account_id").references(Accounts.id).nullable()
    val hitCount = integer("hit_count")
    val lastUsedAt = timestampWithTimeZone("last_used_at")
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}

// =========================================
// Notification Settings
// =========================================
object NotificationSettings : Table("notification_settings") {
    val id = uuid("id")
    val type = varchar("type", 30)
    val isEnabled = bool("is_enabled")
    val frequency = varchar("frequency", 20).nullable()
    val dayOfWeek = varchar("day_of_week", 20).nullable()
    val timeOfDay = time("time_of_day").nullable()
    val thresholdPercent = integer("threshold_percent").nullable()
    val version = integer("version")
    val createdAt = timestampWithTimeZone("created_at")
    val updatedAt = timestampWithTimeZone("updated_at")
    val deletedAt = timestampWithTimeZone("deleted_at").nullable()
    override val primaryKey = PrimaryKey(id)
}
