package com.kakeibo.backend.repository

import com.kakeibo.backend.db.Transactions
import com.kakeibo.backend.db.TransactionTags
import com.kakeibo.backend.db.Categories
import com.kakeibo.backend.db.Accounts
import com.kakeibo.backend.db.Tags
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.javatime.month
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.*

data class TransactionFilter(
    val dateFrom: LocalDate? = null,
    val dateTo: LocalDate? = null,
    val type: String? = null,
    val categoryId: UUID? = null,
    val accountId: UUID? = null,
    val tagIds: List<UUID>? = null,
    val keyword: String? = null,
    val includeDeleted: Boolean = false
)

class TransactionRepository {
    fun findAll(
        filter: TransactionFilter,
        page: Int? = null,
        size: Int = 50,
        sortField: String = "date",
        sortDirection: String = "desc"
    ): Pair<List<ResultRow>, Long> = transaction {
        val query = Transactions.selectAll().apply {
            if (!filter.includeDeleted) andWhere { Transactions.deletedAt.isNull() }
            filter.dateFrom?.let { andWhere { Transactions.date greaterEq it } }
            filter.dateTo?.let { andWhere { Transactions.date lessEq it } }
            filter.type?.let { andWhere { Transactions.type eq it } }
            filter.categoryId?.let { andWhere { Transactions.categoryId eq it } }
            filter.accountId?.let { andWhere { Transactions.accountId eq it } }
            filter.keyword?.let { kw ->
                val escaped = kw.replace("%", "\\%").replace("_", "\\_")
                andWhere { Transactions.memo like "%$escaped%" }
            }
        }

        // Tag filter (AND search)
        filter.tagIds?.takeIf { it.isNotEmpty() }?.let { tagIds ->
            val txIdsWithAllTags = TransactionTags
                .select(TransactionTags.transactionId)
                .where { TransactionTags.tagId inList tagIds }
                .groupBy(TransactionTags.transactionId)
                .having { TransactionTags.tagId.count() eq tagIds.size.toLong() }
                .map { it[TransactionTags.transactionId] }
            query.andWhere { Transactions.id inList txIdsWithAllTags }
        }

        val totalCount = query.count()

        val sortColumn = when (sortField) {
            "amount" -> Transactions.amount
            "date" -> Transactions.date
            else -> Transactions.date
        }
        val order = if (sortDirection == "asc") SortOrder.ASC else SortOrder.DESC
        query.orderBy(sortColumn to order, Transactions.id to SortOrder.DESC)

        if (page != null) {
            query.limit(size).offset(((page - 1) * size).toLong())
        }

        Pair(query.toList(), totalCount)
    }

    fun findById(id: UUID): ResultRow? = transaction {
        Transactions.selectAll().where { Transactions.id eq id }.singleOrNull()
    }

    fun create(
        id: UUID, type: String, amount: Long, currency: String, date: LocalDate,
        memo: String?, categoryId: UUID, accountId: UUID,
        isAutoGenerated: Boolean = false, recurringTransactionId: UUID? = null
    ): ResultRow = transaction {
        val now = OffsetDateTime.now()
        Transactions.insert {
            it[Transactions.id] = id
            it[Transactions.type] = type
            it[Transactions.amount] = amount
            it[Transactions.currency] = currency
            it[Transactions.date] = date
            it[Transactions.memo] = memo
            it[Transactions.categoryId] = categoryId
            it[Transactions.accountId] = accountId
            it[Transactions.isAutoGenerated] = isAutoGenerated
            it[Transactions.recurringTransactionId] = recurringTransactionId
            it[Transactions.version] = 1
            it[Transactions.createdAt] = now
            it[Transactions.updatedAt] = now
        }
        findById(id)!!
    }

    fun update(
        id: UUID, type: String, amount: Long, currency: String, date: LocalDate,
        memo: String?, categoryId: UUID, accountId: UUID, currentVersion: Int
    ): ResultRow? = transaction {
        val now = OffsetDateTime.now()
        val updated = Transactions.update({
            (Transactions.id eq id) and (Transactions.version eq currentVersion)
        }) {
            it[Transactions.type] = type
            it[Transactions.amount] = amount
            it[Transactions.currency] = currency
            it[Transactions.date] = date
            it[Transactions.memo] = memo
            it[Transactions.categoryId] = categoryId
            it[Transactions.accountId] = accountId
            it[Transactions.version] = currentVersion + 1
            it[Transactions.updatedAt] = now
        }
        if (updated > 0) findById(id) else null
    }

    fun softDelete(id: UUID, currentVersion: Int): Boolean = transaction {
        val now = OffsetDateTime.now()
        val updated = Transactions.update({
            (Transactions.id eq id) and (Transactions.version eq currentVersion)
        }) {
            it[Transactions.deletedAt] = now
            it[Transactions.version] = currentVersion + 1
            it[Transactions.updatedAt] = now
        }
        updated > 0
    }

    fun restore(id: UUID): Boolean = transaction {
        val row = findById(id) ?: return@transaction false
        val currentVersion = row[Transactions.version]
        val updated = Transactions.update({ Transactions.id eq id }) {
            it[Transactions.deletedAt] = null
            it[Transactions.version] = currentVersion + 1
            it[Transactions.updatedAt] = OffsetDateTime.now()
        }
        updated > 0
    }

    fun countByCategoryId(categoryId: UUID): Long = transaction {
        Transactions.selectAll().where {
            (Transactions.categoryId eq categoryId) and Transactions.deletedAt.isNull()
        }.count()
    }

    fun reassignCategory(fromCategoryId: UUID, toCategoryId: UUID): Int = transaction {
        Transactions.update({
            (Transactions.categoryId eq fromCategoryId) and Transactions.deletedAt.isNull()
        }) {
            it[Transactions.categoryId] = toCategoryId
            it[Transactions.updatedAt] = OffsetDateTime.now()
        }
    }

    fun sumByAccountAndType(accountId: UUID, type: String): Long = transaction {
        Transactions.select(Transactions.amount.sum())
            .where {
                (Transactions.accountId eq accountId) and
                        (Transactions.type eq type) and
                        Transactions.deletedAt.isNull()
            }.singleOrNull()?.get(Transactions.amount.sum()) ?: 0L
    }

    fun sumByCategoryAndMonth(categoryId: UUID, yearMonth: String): Long = transaction {
        val parts = yearMonth.split("-")
        val year = parts[0].toInt()
        val month = parts[1].toInt()
        val startDate = LocalDate.of(year, month, 1)
        val endDate = startDate.plusMonths(1).minusDays(1)

        Transactions.select(Transactions.amount.sum())
            .where {
                (Transactions.categoryId eq categoryId) and
                        (Transactions.type eq "expense") and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull()
            }.singleOrNull()?.get(Transactions.amount.sum()) ?: 0L
    }

    /**
     * Batch sum of expense amounts grouped by category for a given month.
     * Returns Map<categoryId, totalExpense>.
     */
    fun sumAllCategoriesByMonth(yearMonth: String): Map<UUID, Long> = transaction {
        val parts = yearMonth.split("-")
        val year = parts[0].toInt()
        val month = parts[1].toInt()
        val startDate = LocalDate.of(year, month, 1)
        val endDate = startDate.plusMonths(1).minusDays(1)
        val amountSum = Transactions.amount.sum()

        Transactions.select(Transactions.categoryId, amountSum)
            .where {
                (Transactions.type eq "expense") and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull()
            }
            .groupBy(Transactions.categoryId)
            .associate { row ->
                row[Transactions.categoryId] to (row[amountSum] ?: 0L)
            }
    }

    /**
     * Batch sum of expense amounts grouped by category for an entire year (all 12 months combined).
     * Returns Map<categoryId, totalExpense>.
     */
    fun sumAllCategoriesByYear(year: Int): Map<UUID, Long> = transaction {
        val startDate = LocalDate.of(year, 1, 1)
        val endDate = LocalDate.of(year, 12, 31)
        val amountSum = Transactions.amount.sum()

        Transactions.select(Transactions.categoryId, amountSum)
            .where {
                (Transactions.type eq "expense") and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull()
            }
            .groupBy(Transactions.categoryId)
            .associate { row ->
                row[Transactions.categoryId] to (row[amountSum] ?: 0L)
            }
    }

    fun getDistinctMemos(keyword: String, limit: Int = 10): List<Pair<String, Long>> = transaction {
        val escaped = keyword.replace("%", "\\%").replace("_", "\\_")
        Transactions
            .select(Transactions.memo, Transactions.memo.count())
            .where {
                Transactions.memo.isNotNull() and
                        (Transactions.memo like "%$escaped%") and
                        Transactions.deletedAt.isNull()
            }
            .groupBy(Transactions.memo)
            .orderBy(Transactions.memo.count() to SortOrder.DESC)
            .limit(limit)
            .mapNotNull { row ->
                val memo = row[Transactions.memo]
                if (memo != null) Pair(memo, row[Transactions.memo.count()])
                else null
            }
    }

    fun getMonthlySummary(year: Int, month: Int): Pair<Long, Long> = transaction {
        val startDate = LocalDate.of(year, month, 1)
        val endDate = startDate.plusMonths(1).minusDays(1)

        val income = Transactions.select(Transactions.amount.sum())
            .where {
                (Transactions.type eq "income") and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull()
            }.singleOrNull()?.get(Transactions.amount.sum()) ?: 0L

        val expense = Transactions.select(Transactions.amount.sum())
            .where {
                (Transactions.type eq "expense") and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull()
            }.singleOrNull()?.get(Transactions.amount.sum()) ?: 0L

        Pair(income, expense)
    }

    /**
     * Batch yearly summary: returns Map<month (1-12), Pair<income, expense>>
     * in a single query per type instead of 12 separate queries.
     */
    fun getYearlyMonthlySummary(year: Int): Map<Int, Pair<Long, Long>> = transaction {
        val startDate = LocalDate.of(year, 1, 1)
        val endDate = LocalDate.of(year, 12, 31)
        val monthExpr = Transactions.date.month()
        val amountSum = Transactions.amount.sum()

        val incomeByMonth = mutableMapOf<Int, Long>()
        val expenseByMonth = mutableMapOf<Int, Long>()

        Transactions.select(monthExpr, Transactions.type, amountSum)
            .where {
                (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull() and
                        (Transactions.type inList listOf("income", "expense"))
            }
            .groupBy(monthExpr, Transactions.type)
            .forEach { row ->
                val month = row[monthExpr]
                val type = row[Transactions.type]
                val amount = row[amountSum] ?: 0L
                when (type) {
                    "income" -> incomeByMonth[month] = amount
                    "expense" -> expenseByMonth[month] = amount
                }
            }

        (1..12).associateWith { month ->
            Pair(incomeByMonth[month] ?: 0L, expenseByMonth[month] ?: 0L)
        }
    }

    fun getCategoryBreakdown(year: Int, month: Int, type: String): List<Triple<UUID, String, Long>> = transaction {
        val startDate = LocalDate.of(year, month, 1)
        val endDate = startDate.plusMonths(1).minusDays(1)

        (Transactions innerJoin Categories)
            .select(Transactions.categoryId, Categories.name, Transactions.amount.sum())
            .where {
                (Transactions.type eq type) and
                        (Transactions.date greaterEq startDate) and
                        (Transactions.date lessEq endDate) and
                        Transactions.deletedAt.isNull() and
                        Categories.deletedAt.isNull()
            }
            .groupBy(Transactions.categoryId, Categories.name)
            .orderBy(Transactions.amount.sum() to SortOrder.DESC)
            .map { row ->
                Triple(
                    row[Transactions.categoryId],
                    row[Categories.name],
                    row[Transactions.amount.sum()] ?: 0L
                )
            }
    }

    fun findUpdatedSince(since: OffsetDateTime, limit: Int = 1000): List<ResultRow> = transaction {
        Transactions.selectAll()
            .where { Transactions.updatedAt greater since }
            .orderBy(Transactions.updatedAt)
            .limit(limit)
            .toList()
    }

    fun findRecentTransactions(limit: Int = 10): List<ResultRow> = transaction {
        Transactions.selectAll()
            .where { Transactions.deletedAt.isNull() }
            .orderBy(Transactions.date to SortOrder.DESC, Transactions.createdAt to SortOrder.DESC)
            .limit(limit)
            .toList()
    }
}
